Recetapp/Apps/Recetas/urls.py
from django.urls import path

from . import views

app_name = 'recetas'
urlpatterns = [
    path('', views.index, name='index'),
    path('recetas/', views.recetas, name='recetas'),
    path('crear-receta', views.crear_receta, name='crear-receta'),
    path('guardar_receta', views.guardar_receta, name='guardar-receta')
]

Recetapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Recetapp.Apps.Recetas.urls')),
    path('admin/', admin.site.urls)
]

Recetapp/Apps/Recetas/models.py
from django.db import models


# Create your models here.

class Unidad(models.Model):
    nombre = models.CharField(max_length=45)
    abreviacion = models.CharField(max_length=7)

    def __str__(self):
        return self.nombre


class Tienda(models.Model):
    nombre = models.CharField(max_length=45)
    horario = models.CharField(max_length=70)

    def __str__(self):
        return self.nombre


class Ingrediente(models.Model):
    nombre = models.CharField(max_length=50)
    unidad = models.ForeignKey(Unidad, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.nombre


class Receta(models.Model):
    nombre = models.CharField(max_length=50)
    tiempo = models.IntegerField(blank=True, null=True)
    vegano = models.BooleanField(null=True)
    descripcion = models.CharField(max_length=450, null=True)
    ingredientes = models.ManyToManyField(Ingrediente, through='RecetaIngrediente')

    def __str__(self):
        return self.nombre


class RecetaIngrediente(models.Model):
    receta = models.ForeignKey(Receta, on_delete=models.CASCADE)
    ingrediente = models.ForeignKey(Ingrediente, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=1, blank=True, null=True)

    def __str__(self):
        return "Receta: " + str(self.receta) + " | " + str(self.cantidad) + " " + str(self.ingrediente)


class TiendaIngrediente(models.Model):
    tienda = models.ForeignKey(Tienda, on_delete=models.CASCADE)
    ingrediente = models.ForeignKey(Ingrediente, on_delete=models.CASCADE)
    precio = models.FloatField(null=True)

    def __str__(self):
        return "Tienda: " + str(self.tienda) + " | Ingrediente: " + str(self.ingrediente)

Recetapp/Apps/Recetas/views.py
from django.shortcuts import render, redirect
from Recetapp.Apps.Recetas.models import Receta, RecetaIngrediente


# Create your views here.

def index(request):

    return render(request, "index.html")


def recetas(request):

    recetas = Receta.objects.all()

    return render(request, "recetas.html", {"recetas": recetas})


def crear_receta(request):
    

    return render(request, "crear_receta.html")


def guardar_receta(request):

    if request.method == "POST":

        nombre = request.POST["nombre"]
        tiempo = request.POST["tiempo"]
        # vegano = request.POST["vegano"]
        descripcion = request.POST["descripcion"]

        print(f"Nombre: {nombre}")
        print(f"Tiempo: {tiempo}")
        print(f"Vegano: {vegano}")
        print(f"Descripcion: {descripcion}")

        receta = Receta(
            nombre = nombre,
            tiempo = tiempo,
            # vegano = vegano,
            descripcion = descripcion
        )

        receta.save()
    
    redirect('recetas:recetas')

Recetapp/Apps/Recetas/templates/crear_receta.html
<!-- Con este comando esta plantilla se integra en layout.html -->
{% extends 'layout.html' %}

<!-- Bloque para el título de la plantilla -->

{% block title %}

    Crear Receta

{% endblock %}

<!-- Contenido que irá al bloque de contenido del layout -->

{% block content %}

    <div class="container">
        <form method="POST" action="{% url 'recetas:guardar-receta' %}">
            
            {% csrf_token %}

            <div class="row my-4">
                <div class="col">
                    <label for="nombre" class="form-label">Example label</label>
                    <input type="text" class="form-control" placeholder="First name" aria-label="First name">
                </div>
                <div class="col">
                    <label for="tiempo" class="form-label">Example label</label>
                    <input type="number" class="form-control" placeholder="Last name" aria-label="Last name">
                </div>
            </div>
            <div class="row my-4">
                <div class="col">
                    <label for="descripcion" class="form-label">Descripción de la receta</label>
                    <textarea class="form-control" id="descripcion" rows="3"></textarea>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>

{% endblock %}

Recetapp/Apps/Recetas/templates/index.html
<!-- Con este comando esta plantilla se integra en layout.html -->
{% extends 'layout.html' %}

<!-- Bloque para el título de la plantilla -->

{% block title %}

    Home

{% endblock %}

<!-- Contenido que irá al bloque de contenido del layout -->

{% block content %}

    <div class="container-fluid my-5">
        <div class="container">
            <header>
                <h1 class="text-center">Bienvenido/a a Recetapp</h1>
                <p>Recetapp nació de la necesidad de poder ahorrar tiempo para poder hacer la lista de compras para la comida. También de la idea de poder hacer mejores recetas, más ricas, ahorrando tiempo y dinero. ¡Guten appetit!</p>
            </header>
        </div>
    </div>

    <div class="container my-5">
        <h2>Recetapp es un proyecto hecho con <strong>Django</strong></h2>
        
        <p>Django de un framework web escrito en Python. Recetapp es un proyecto para poder practicar django y también para poder gestionar nuestras recetas y compras.</p>
    </div>


{% endblock %}

Recetapp/Apps/Recetas/templates/layout.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recetapp | {% block title %}{% endblock %}</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>

    <!-- Barra de navegación -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-2">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'recetas:index' %}">Inicio</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="{% url 'recetas:recetas' %}">Recetas</a>
                    <a class="nav-link" href="{% url 'recetas:crear-receta' %}">Crear Receta</a>
                    <a class="nav-link" href="http://127.0.0.1:8000/admin/">Sitio de administrador</a>
                    <!---<a class="nav-item nav-link disabled" href="http://127.0.0.1:8000/admin/">Disabled</a>--->
                </div>
            </div>
        </div>
    </nav>
    <main>
        
        {% block content %}

            <!-- Código que viene desde los templates -->

        {% endblock %}

        <div class="container-fluid text-center py-3">
            <footer>
                Recetapp | Derechos Reservados | {% now "d/m/y" %}
            </footer>
        </div>

        <!--- Bootstrap --->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    </main>
</body>
</html>

Recetapp/Apps/Recetas/templates/recetas.html
<!-- Con este comando esta plantilla se integra en layout.html -->
{% extends 'layout.html' %}

<!-- Bloque para el título de la plantilla -->

{% block title %}

    Recetas

{% endblock %}

<!-- Contenido que irá al bloque de contenido del layout -->

{% block content %}
    

    <div class="container-fluid">
        <header>
            <h1 class="text-center">¡Recetas!</h1>
            <p>En esta sección puedes revisar todas las recetas que tenemos para tí. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deserunt quidem atque corporis quas asperiores eaque illo perspiciatis obcaecati vitae cum!</p>
        </header>
    </div>

    <div class="container">
        <div class="row">

            {% for receta in recetas %}
            
                <div class="col-xl-4 col-sm-6 col-12 p-3 d-flex justify-content-center">
                    <div class="card" style="width: 16rem;">
                        <div class="card-body bg-info text-white">
                          <h4 class="card-title">{{ receta.nombre }}</h4>
                          <p class="card-text">{{ receta.descripcion }}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><b>Tiempo:</b> {{ receta.tiempo }}</li>
                            <li class="list-group-item">
                                {% if receta.vegano == True %}
                                    <b>Es vegano:</b> Sí
                                {% else %}
                                    <b>Es vegano:</b> No
                                {% endif %}
                            </li>
                            {% for recetaingrediente in receta.recetaingrediente_set.all %}
                                <li class="list-group-item"><b>{{ recetaingrediente.cantidad }}</b> {{ recetaingrediente.ingrediente }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

            {% endfor %}

        </div>
    </div>

{% endblock %}